language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

# install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

# run tests
script: 
  - "nosetests --with-coverage --cover-package=quora"

branches:
  only:
    - master

# email notifications
notifications:
  email:
    on_success: never # for now
    on_failure: never # for now